services:
  frontend:
    image: ${DOCKERHUB_USERNAME}/frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=${BACKEND_URL}  
    restart: unless-stopped
