services:
  frontend:
    image: ${DOCKERHUB_USERNAME}/frontend:latest
    ports:
      - "3000:3000"

# services:
#   backend:
#     build:
#       context: ../backend-crud
#       dockerfile: Dockerfile
#     ports:
#       - "5000:5000"
#     networks:
#       - mern-network

#   frontend:
#     image: yourdockerhubusername/frontend:latest
#     ports:
#       - "3000:3000"
#     networks:
#       - mern-network

#   mongo:
#     image: mongo
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo-data:/data/db
#     networks:
#       - mern-network

# networks:
#   mern-network:
#     driver: bridge

# volumes:
#   mongo-data:
