name: Build & Push Docker Images

on:
  push:
    branches: [main]

jobs:

  build-and-push-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
  
  deploy:
    needs: build-and-push-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "\
          echo 'DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}' > /home/ec2-user/E-commerce-UI/.env && \
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest && \
          docker-compose -f /home/ec2-user/E-commerce-UI/docker-compose.yml up -d frontend \
          "
